### PR TITLE
Fixed: Add ForeignEditionId to books endpoint

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Database Migration
NO

* Closes #2389

### CODE REVIEW

**Comment by mynameisbogdan** [comment]
@blampe you can test this by using `ghcr.io/linuxserver-labs/prarr:readarr-api-books-main-edition`

**Comment by blampe** [comment]
> @blampe you can test this by using `ghcr.io/linuxserver-labs/prarr:readarr-api-books-main-edition`

Thanks, I'll try to confirm this works tonight.

**Comment by blampe** [comment]
@mynameisbogdan I can confirm this works as expected 🙌

Unrelated, but is the docker build documented somewhere? That would be helpful for local dev.

**Comment by mynameisbogdan** [comment]
> I can confirm this works as expected 🙌

Good to hear, but we'll have to wait for a code review from @ta264. 

Until then I can rebase this periodically so you can pull what's basically nightly + this changes.

> Unrelated, but is the docker build documented somewhere? That would be helpful for local dev.

[Here](https://github.com/linuxserver-labs/prarr) and [here](https://github.com/linuxserver/docker-readarr/tree/nightly), but these use the azure builds from PRs that are pushed to branches in this repository. So it won't help you that much, since your need to build the backend, the frontend and then package it. After all this you can use the artifacts in a Dockerfile instead of a tarball.

**Comment by blampe** [comment]
@mynameisbogdan FWIW I have two instances using your branch (they report their version as 0.2.2.1928) and I recently noticed one of them has become unusable because almost every page generates a traceback similar to https://github.com/Readarr/Readarr/issues/1514 / https://github.com/Readarr/Readarr/issues/2153. I'm not sure if this is actually related to your branch or just a separate issue. In any case, there might be a lingering bug where the import list's edition somehow gets the consumer into a bad state. (Would an audiobook edition break things if the consumer is searching for book editions?)

```
[v0.2.2.1928] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Readarr.Api.V1.Books.BookResourceMapper.ToResource(Book model) in ./Readarr.Api.V1/Books/BookResource.cs:line 61
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Readarr.Api.V1.Books.BookResourceMapper.ToResource(IEnumerable`1 models) in ./Readarr.Api.V1/Books/BookResource.cs:line 121
   at Readarr.Api.V1.Books.BookControllerWithSignalR.MapToResource(List`1 books, Boolean includeAuthor) in ./Readarr.Api.V1/Books/BookControllerWithSignalR.cs:line 69
   at Readarr.Api.V1.Books.BookController.GetBooks(Nullable`1 authorId, List`1 bookIds, String titleSlug, Boolean includeAllAuthorBooks) in ./Readarr.Api.V1/Books/BookController.cs:line 93
   at lambda_method155(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/BufferingMiddleware.cs:line 27
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/IfModifiedMiddleware.cs:line 40
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/CacheHeaderMiddleware.cs:line 32
   at Readarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/StartingUpMiddleware.cs:line 37
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/UrlBaseMiddleware.cs:line 26
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Readarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by mynameisbogdan** [comment]
Well that occurs only when the app finds more than one `Monitored` editions.

**Comment by politician** [comment]
@ta264 Would you mind reviewing this PR? Without it, two Readarr instances will most likely be only partially in sync. In my case it only synced 56% of books. It went up 100% after I used the code in this PR (thanks @mynameisbogdan !)

**Comment by politician** [comment]
@mynameisbogdan I can see you commit a lot to this repo, why can't this PR just be merged? Thanks.

**Comment by politician** [comment]
Thank you!

**Comment by mynameisbogdan** [comment]
And it was because nobody was wiling to test it. 🥲 

👍

**Pull request merged**
