### PR TITLE
Fixed: Check for unexpected parent tags to fix GoodReads Series

### LINKED ISSUE #1549: GoodReads Series Sync Lists Showing Zero Results For Valid List IDs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Goodreads Series Lists are returning zero results when List Sync is ran.

- Test Passing for List
`2022-02-26 06:47:15.5|Trace|Http|Req: 144 [POST] /api/v1/importlist/test (from 192.168.1.201)
2022-02-26 06:47:15.5|Debug|GoodreadsProxy|Getting Series with GoodreadsId of 299373
2022-02-26 06:47:15.5|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/series/299373?key=dcX1YH52UMjs6lznO2MuSg&_nc=1&format=xml
2022-02-26 06:47:15.5|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IImportList>
2022-02-26 06:47:15.5|Trace|Http|Res: 144 [POST] /api/v1/importlist/test: 200.OK (10 ms)
2022-02-26 06:47:15.5|Debug|Api|[POST] /api/v1/importlist/test: 200.OK (10 ms)`

- Initiating Sync with List that passed test. Results show zero list items, though the returned XML document has 6 books listed.
`2022-02-26 06:48:45.1|Info|ImportListSyncService|Starting Import List Sync
2022-02-26 06:48:45.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-02-26 06:48:45.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-02-26 06:48:45.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-02-26 06:48:45.1|Debug|FetchAndParseImportListService|Available import lists 1
2022-02-26 06:48:45.1|Debug|GoodreadsProxy|Getting Series with GoodreadsId of 299373
2022-02-26 06:48:45.1|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/series/299373?key=dcX1YH52UMjs6lznO2MuSg&_nc=1&format=xml
2022-02-26 06:48:45.1|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IImportList>
2022-02-26 06:48:45.1|Debug|FetchAndParseImportListService|Found 0 from Goodreads Series
2022-02-26 06:48:45.1|Debug|FetchAndParseImportListService|Found 0 reports
2022-02-26 06:48:45.1|Info|ImportListSyncService|Processing 0 list items
2022-02-26 06:48:45.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-02-26 06:48:45.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-02-26 06:48:45.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-02-26 06:48:45.1|Debug|AuthorMetadataRepository|0 author metadata up to date; Updating 0, Adding 0 author metadata entries.
2022-02-26 06:48:45.1|Trace|EventAggregator|Publishing AuthorsImportedEvent
2022-02-26 06:48:45.1|Trace|EventAggregator|AuthorsImportedEvent -> AuthorAddedHandler
2022-02-26 06:48:45.1|Trace|EventAggregator|AuthorsImportedEvent <- AuthorAddedHandler`

### Expected Behavior

Expecting Goodreads Series Lists to return series info and listed books on Sync List task, (if no current Author) importing new Author, marking books from list as Wanted per List settings.

### Steps To Reproduce

In Settings / Import Lists, add new list of type Goodreads Series. 
Use valid series ID, IE 299373
Save list.
In System / Tasks run Import List Sync task
View results

### Environment

```markdown
Version: 0.1.1.1259
Package Version: nightly-9b5c3ee by hotio
.NET Core: Yes (6.0.2)
Docker: Yes
DB Migration: 21
```

### What branch are you running?

Nightly

### Trace Logs?

The reason for the other lists all failing and being skipped is they all returned zero results in the last sync, but Testing a list clears its "Failed" status.

[TestList.txt](https://github.com/Readarr/Readarr/files/8146642/TestList.txt)
[SyncLists.txt](https://github.com/Readarr/Readarr/files/8146643/SyncLists.txt)

[AB#2662](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2662)

### PR DESCRIPTION
**Pull request by santschi**
#### Database Migration
NO

#### Description
This should fix the Goodreads Series Importlists

#### Issues Fixed or Closed by this PR

* Fixes #1549

### CODE REVIEW

**Comment by santschi** [comment]
@Qstick Since I am not a collaborator I cannot add reviewers. If you have some spare time I'd appreciate a look.

**Comment by Qstick** [comment]
@santschi my familiarity with this part of the code is not great. This was always @ta264

**Comment by santschi** [comment]
Ah well. Thanks anyway! I'll just leave the PR open and see what happens

**Review by Budlyte — DISMISSED** [review]

**Comment by mynameisbogdan** [comment]
LGTM 👍

**Review by mynameisbogdan — DISMISSED** [review]

**Review by mynameisbogdan — APPROVED** [review]

**Pull request merged**
