### PR TITLE
wiki fixups & fix builds & various

### LINKED ISSUE #159: Pull Sonarr commit 'Fixed: Empty list message for System: Events'
Pull https://github.com/Sonarr/Sonarr/commit/a23639e62ee5e2106831c10d51b6a4d6ba569fdc

```
git cherry-pick a23639e62ee5e2106831c10d51b6a4d6ba569fdc
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1099](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1099)

### LINKED ISSUE #251: Pull Sonarr commit 'Fixed: Indicate unchecking Replace Illegal Characters will remove them'
Pull https://github.com/Sonarr/Sonarr/commit/4bacc356056bfb5c43bae9cbdd4c6b2aa4b31fa3

```
git cherry-pick 4bacc356056bfb5c43bae9cbdd4c6b2aa4b31fa3
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#968](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/968)

### LINKED ISSUE #278: Pull Sonarr commit 'New: Don't close manual import when clicking outside the modal'
Pull https://github.com/Sonarr/Sonarr/commit/fd608fd4113bd1d6fde42bca4d9879f826a8c6a9

```
git cherry-pick fd608fd4113bd1d6fde42bca4d9879f826a8c6a9
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1020](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1020)

### LINKED ISSUE #281: Pull Sonarr commit 'Queue status/timeleft improvements'
Pull https://github.com/Sonarr/Sonarr/commit/910de6d94a4482e82e295153e01c299460af2d2d

```
git cherry-pick 910de6d94a4482e82e295153e01c299460af2d2d
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#963](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/963)

### LINKED ISSUE #295: Pull Sonarr commit 'Log contents on api errors during tests.'
Pull https://github.com/Sonarr/Sonarr/commit/f2e1b4e43549695afacee5c87cca368e8fa30905

```
git cherry-pick f2e1b4e43549695afacee5c87cca368e8fa30905
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#973](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/973)

### LINKED ISSUE #304: Pull Sonarr commit 'Fixed flaky test.'
Pull https://github.com/Sonarr/Sonarr/commit/f846e0c031d74914d3a02626597df583422164e0

```
git cherry-pick f846e0c031d74914d3a02626597df583422164e0
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#987](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/987)

### PR DESCRIPTION
**Pull request by bakerboy448**
wiki fixups

Closes #159 
Closes #251
Closes #278
Closes #281 
Closes #295
Closes #304

### CODE REVIEW

**Comment by Qstick** [comment]
Rebase

**Comment by bakerboy448** [comment]
already ahead of ya as soon as i saw the extra commits :D

**Comment by Qstick** [comment]
rebase the revert out, already had it local and pushed

**Comment by bakerboy448** [comment]
done; can merge whenever if needed; rebasing qbit momentarily

otherwise i'm planning on keeping to add ez cherrypicks to this branch, will open another again if needed

**Pull request merged**
