### PR TITLE
Add a regex parser for the MyAnonaMouse tracker

### PR DESCRIPTION
**Pull request by rvetrsek**
#### Database Migration
NO

#### Description
I added a regex to the ReportAlbumTitleRegex parser to enable parsing results from the MyAnonaMouse tracker.

#### Todos
- [x] Tests

### CODE REVIEW

**Review by ta264 — CHANGES_REQUESTED** [review]
Thanks very much for the contribution!

Please can you add some cases to the unit tests to verify it works?

**Comment by rvetrsek** [comment]
@ta264 No problem. I have now added a couple of test cases, as requested.

**Comment by Qstick** [comment]
This parses wrong for books with “by” in the title like 

Ex. 
“America by design by David Noble [eng]” or anything else

That was first book that came up in a google search, also if by is in another word like megabyte it parses wrong. Examples like this should be in test cases

A9F71E3D-10F7-4533-B4B7-E3872CFFD902
4719F7D3-3FB5-4084-BD06-585CA95808B7

A more popular example “the great gatsby”

**Comment by ta264** [comment]
I think this should be better is latest builds but if not please do reopen against develop

**Comment by ta264** [comment]
And thanks for the contribution!

**Pull request closed without merging**
