### PR TITLE
New: Optionally use Environment Variables for settings in config.xml

### LINKED ISSUE #3447: Pull Sonarr commit 'New: Optionally use Environment Variables for settings in config.xml'
Pull https://github.com/Sonarr/Sonarr/commit/d051dac12c8b797761a0d1f3b4aa84cff47ed13d

```
git cherry-pick -ex d051dac12c8b797761a0d1f3b4aa84cff47ed13d
```

This commit has 2 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### PR DESCRIPTION
**Pull request by sillock1**
#### Database Migration
 NO

#### Description
Pulled from upstream https://github.com/Sonarr/Sonarr/pull/6746/files
The auth required option hasn't been brought over as the `UiAuthorizationHandler` wasn't originally pulled downstream like the other arrs. Not sure if this was intentional or whether it just happened to be missed.

* Fixes #3447

### CODE REVIEW

**Comment by mynameisbogdan** [comment]
I'll take a look at what work implies pulling `UiAuthorizationHandler` before taking a decision on merging this one.

**Comment by mynameisbogdan** [comment]
FYI this needs to close #3496 as well.

**Comment by alapshin** [comment]
I would like to thank @sillock1 for taking time to implement this feature for *arr apps.

It would be really great to see these changes merged to have feature parity between all major *arr apps. 

Right now, I'm working on new modules for NixOS utilizing these changes and have a working prototype for all other apps but planning to wait until all apps have this functionality at stable/main version.

**Comment by mynameisbogdan** [comment]
Best you can expect from Readarr is a develop release.

**Comment by alapshin** [comment]
> Best you can expect from Readarr is a develop release.

No problem with that. I didn't know that Readarr didn't have stable release yet and was looking at Sonarr with their main vs. develop version split. NixOS/Nixpkgs use develop releases of Readarr anyway.

**Comment by sillock1** [comment]
> FYI this needs to close #3496 as well.

I've pulled that commit into this PR

**Comment by sillock1** [comment]
> I'll take a look at what work implies pulling `UiAuthorizationHandler` before taking a decision on merging this one.

What was your verdict on this?

**Comment by mynameisbogdan** [comment]
Didn't looked into it since I'm taking a break. 😺

**Comment by mynameisbogdan** [comment]
Just pushed it, feel free to rebase.

**Comment by mynameisbogdan** [comment]
Thanks for your contribution.

**Pull request merged**
