### PR TITLE
Fixed: Support new states in qBittorrent 5 preventing downloads from being removed

### LINKED ISSUE #3463: Pull Sonarr commit 'New: Support stoppedUP and stoppedDL states from qBittorrent'
Pull https://github.com/Sonarr/Sonarr/commit/73a4bdea5247ee87e6bbae95f5325e1f03c88a7f

```
git cherry-pick -ex 73a4bdea5247ee87e6bbae95f5325e1f03c88a7f
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #3777: Readarr no longer removes downloads from qBittorrent
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

Ever since qBittorrent 5.0.0, Readarr no longer seems to interact correctly with qBittorrent. Two things stand out:
- Completed downloads are no longer removed from qBittorrent queue (with or without seeding time).
- Every now and then a download which is still present in qBittorrent, disappears from the Activity tab in Readarr.

I've downgraded qBittorrent to 4.6.7, and everything works fine again. I will attach two trace logs, where I will download the same file in Readarr twice. I'm suspecting qBittorrent has new statuses that Readarr isn't expecting (yet), and this leaves Readarr waiting forever for the correct status in the json response. (Might be this? https://github.com/Readarr/Readarr/issues/3463)

### Expected Behavior

Readarr should remove completed downloads from qBittorrent queue, if this is enabled in Readarr settings. 

### Steps To Reproduce

Enable 'Automatically import completed downloads from download client' in Settings > Download Clients, and enable 'Remove imported downloads from download client history' in qBittorrent download client settings. Then, download a book (an audiobook in my case), and when completed, check the media folder to see the new file present, but also check the download folder to see the file present still. And also, check qBittorrent queue to see the torrent still sitting there, completed. 

### Environment

```markdown
- OS: Debian 12
- Readarr: 0.4.0.2634
- Docker Install: yes (Linuxserver.io)
- Using Reverse Proxy: no
- Browser: - 
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs?

[qbittorrent4.6.7.readarr.trace.txt](https://github.com/user-attachments/files/17229202/qbittorrent4.6.7.readarr.trace.txt)
[qbittorrent5.0.0.readarr.trace.txt](https://github.com/user-attachments/files/17229270/qbittorrent5.0.0.readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

### LINKED ISSUE #3819: Pull Sonarr commit 'Fixed: Initial state for qBittorrent v5.0'
Pull https://github.com/Sonarr/Sonarr/commit/ff724b7f4099284b8062f1625cf07b7822782edf

```
git cherry-pick -ex ff724b7f4099284b8062f1625cf07b7822782edf
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### PR DESCRIPTION
**Pull request by brokenalarms**
Database Migration
NO
Description

Fixes Readarr no longer being able to complete downloads in QBittorrent 5 and therefore not being able to add books to Calibre.

Issue and cause identified [here](https://www.reddit.com/r/sonarr/comments/1fvg31u/solved_issues_with_qbittorrent_500_not_importing/)

This has been fixed in Sonarr and Radarr, but the qBitTorrent file was not cleanly applicable from these projects, so I manually added and expanded the test cases.

Fixes #3777
Closes https://github.com/Readarr/Readarr/issues/3819
Closes https://github.com/Readarr/Readarr/issues/3463

### CODE REVIEW

**Comment by bakerboy448** [comment]
Please tty to ensure it builds locally....otherwise watch the CI / checks for the PR.

Build failed.

**Comment by brokenalarms** [comment]
I know, just putting up the WIP per the instructions.

Was hoping it was simple enough to just work...I usually do iOS and JS, so will need to install cs framework etc tomorrow on the Mac to dig in further.

-------- Original Message --------

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
also include https://github.com/Readarr/Readarr/issues/3819 and please cherry pick the commits to maintain the authorship and ensuring nothing is missed

**Comment by brokenalarms** [comment]
yeah trying to just fix it without actually compiling to check wasn't going to work 😅 
now set up dev env, built and fixed obvious issue. Also merged in #3819 and resolved merge conflict. thanks!

**Comment by brokenalarms** [comment]
the failing test `successful_book_search` doesn't seem related, since it's failing in separate PR #3861 as well... 🤔

**Comment by bakerboy448** [comment]
commits need to be redone and squashed down into just the 2 commits to be cherry picked from sonarr...

**Comment by brokenalarms** [comment]
Maybe I'm misunderstanding - I couldn't just cherry pick the state commit, there's differences in the file, so I had to do myself. I cherry picked the other one and preserved the author.

I had assumed all commits on the feature branch would be squashed on merge, but I can rewrite to just my commit and the sonarr-picked one.

EDIT: Huh, ok, I could directly merge in the Sonarr one, the files looked like they were not identical per product. Well, I still did it all myself manually 😅 

Reverted my changes and made it just the two original author commits.

-------- Original Message --------

**Review by bakerboy448 — CHANGES_REQUESTED** [review]
relevant CI check failed
`should_be_removable_and_should_allow_move_files_if_max_seedingtime_reached_and_paused`

**Comment by bakerboy448** [comment]
the cherry picks also got mixed together

- edit the failing goodreads test should now be fixed; so once your reset on upstream shouldn't have any non-commit related test failing

see azure build results at https://dev.azure.com/Readarr/Readarr/_build?definitionId=1&_a=summary

- hard reset on upstream/develop
- cherrypick New: Support stoppedUP and stoppedDL states from qBittorrent
- apply relevant readarr changes to get build and tests to pass locally
- append the cherrypicked commit
- cherrypick Fixed: Initial state for qBittorrent v5.0
- apply relevant readarr changes to get build and tests to pass locally
- append the cherrypicked commit
- force push the branch
then we should be good

if you want to skip the local build and test and let the CI

- hard reset on upstream/develop
- cherrypick New: Support stoppedUP and stoppedDL states from qBittorrent
- apply relevant readarr changes
- append the cherrypicked commit
- force push the branch
wait for and review CI
repeat if necessary

- cherrypick Fixed: Initial state for qBittorrent v5.0
- apply relevant readarr changes
- append the cherrypicked commit
- force push the branch
wait for and review CI
repeat if necessary

then we should be good

**Review by bakerboy448 — APPROVED** [review]

**Pull request merged**
