### PR TITLE
New: On Delete Notifications

### LINKED ISSUE #763: Pull Sonarr commit 'New: On Delete Notifications'
Pull https://github.com/Sonarr/Sonarr/commit/c91fabcf2d14afda7dc689c8e2a73edba50c2639

```
git cherry-pick -ex c91fabcf2d14afda7dc689c8e2a73edba50c2639
```

This commit has 15 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1052](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1052)

### LINKED ISSUE #767: Pull Sonarr commit 'Consistent types for on delete custom script events'
Pull https://github.com/Sonarr/Sonarr/commit/02a46349a289753aeb61fc262dbf509e4b21d581

```
git cherry-pick -ex 02a46349a289753aeb61fc262dbf509e4b21d581
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1053](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1053)

### LINKED ISSUE #768: Pull Sonarr commit 'Fixed: Label for 'On Episode File Delete''
Pull https://github.com/Sonarr/Sonarr/commit/39ca348666032d5f5ee9d44c39d731af679a2896

```
git cherry-pick -ex 39ca348666032d5f5ee9d44c39d731af679a2896
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#647](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/647)

### LINKED ISSUE #984: Pull Sonarr commit 'Add missing On Delete Notifications to Mailgun notifications'
Pull https://github.com/Sonarr/Sonarr/commit/a824fa44d21328d9c8bbb1ccfd6d247d4ff5c888

```
git cherry-pick -ex a824fa44d21328d9c8bbb1ccfd6d247d4ff5c888
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#514](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/514)

### LINKED ISSUE #1288: Pull Sonarr commit 'Fixed: On Delete events for Custom Scripts not being executed'
Pull https://github.com/Sonarr/Sonarr/commit/cd30175308dd8d500d7d0abebbf66c9fe9c95f50

```
git cherry-pick -ex cd30175308dd8d500d7d0abebbf66c9fe9c95f50
```

This commit has 1 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1775](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1775)

### PR DESCRIPTION
**Pull request by RetroDadson**
#### Database Migration
YES - 21

#### Description
Adds various on delete notifications to various notification providers

#### Todos
- [x] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)
- [x] Translate all values within ./frontend/src/Settings/Notifications/Notifications/Notification.js
- [x] Delete notifications for various providers

#### Issues Fixed or Closed by this PR

* Fixes #763
* Fixes #767
* Fixes #768
* Fixes #984
* Fixes #1288

### CODE REVIEW

**Comment by RetroDadson** [comment]
Still to do:
 - [x] Custom Script
 - [ ] Goodreads (all types)
 - [x] Notifarr (@austinwbest what variables for each Delete type do you want?)
 - [x] Webhook

CustomScript/Webhook/Notifarr variables to be defined before implementation of those

**Comment by austinwbest** [comment]
> Still to do:
>  - [ ] Custom Script
>  - [ ] Goodreads (all types)
>  - [ ] Notifarr (@austinwbest what variables for each Delete type do you want?)
>  - [ ] Webhook
> 
> CustomScript/Webhook/Notifarr variables to be defined before implementation of those

I think just the common stuff would be fine for all of em really. What you did in radarr & sonarr seems sufficient right?

**Comment by RetroDadson** [comment]
> > Still to do:
> > 
> > * [ ]  Custom Script
> > * [ ]  Goodreads (all types)
> > * [ ]  Notifarr (@austinwbest what variables for each Delete type do you want?)
> > * [ ]  Webhook
> > 
> > CustomScript/Webhook/Notifarr variables to be defined before implementation of those
> 
> I think just the common stuff would be fine for all of em really. What you did in radarr & sonarr seems sufficient right?

That is what I thought, I thought I would check if you wanted anything specific in Notifiarr really :)

**Comment by austinwbest** [comment]
I think I mentioned with sonarr, knowing how many files where deleted and the size. I think you or Markus mentioned the deleted files is a bool instead of int but maybe a file list of deleted files or something that can be counted or displayed. Up to you really but I thought that would be good info in all of them really

**Comment by RetroDadson** [comment]
> I think I mentioned with sonarr, knowing how many files where deleted and the size. I think you or Markus mentioned the deleted files is a bool instead of int but maybe a file list of deleted files or something that can be counted or displayed. Up to you really but I thought that would be good info in all of them really

Yeah so it's still a boolean, I think the issue with that in my mind though is that if it is deleting the files you then should get a file deletion notification each time to make up for it.

**Comment by RetroDadson** [comment]
@bakerboy448  you need to do anything on the wiki for this one?

**Comment by bakerboy448** [comment]
Think just needs the custom script page updated if you don't mind 🥸  and the on delete setting(s) added to connect on the settings page

**Review by Qstick — APPROVED** [review]

**Pull request merged**
